import type { ClinicDataForm } from "@/lib/clinic-data-types";

export const CLINIC_DATA_MOCK: ClinicDataForm = {
  gerais: {
    nomeClinica: "Clínica Sorriso Premium",
    nomeFantasia: "Sorriso Premium",
    razaoSocial: "Sorriso Premium Odontologia Ltda",
    cnpj: "12.345.678/0001-90",
    inscricaoEstadual: "10.20.30-4",
    inscricaoMunicipal: "12345678",
    cnae: "8630-5/03 - Atividade odontológica",
    dataFundacao: "2018-03-15",
    descricao:
      "Clínica odontológica completa com foco em estética, reabilitação oral e atendimento humanizado.",
    especialidades: "Clínica Geral, Ortodontia, Implantodontia, Endodontia, Periodontia",
    exibirDescricaoDocumentos: true,
  },
  endereco: {
    cep: "01310-100",
    rua: "Av. Paulista",
    numero: "1000",
    complemento: "Sala 1201",
    bairro: "Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    pais: "Brasil",
  },
  contatos: {
    telefonePrincipal: "(11) 3456-7890",
    whatsapp: "(11) 97777-6666",
    telefoneSecundario: "(11) 3456-7891",
    email: "contato@sorrisopremium.com.br",
    site: "https://sorrisopremium.com.br",
    instagram: "@sorrisopremium",
    facebook: "sorrisopremium",
    linkedin: "clinica-sorriso-premium",
    horarioContato: "Seg a Sex, 08:00 às 18:00",
  },
  responsavel: {
    nome: "Dr. Carlos Mendes",
    cpf: "123.456.789-00",
    rg: "12.345.678-9",
    cro: "12345",
    ufCro: "SP",
    especialidade: "Clínica Geral / Implantodontia",
    telefone: "(11) 98888-7777",
    email: "carlos.mendes@sorrisopremium.com.br",
    fotoUrl: "",
    assinaturaUrl: "",
    carimboUrl: "",
  },
  horario: [
    { day: "segunda", label: "Segunda", open: "08:00", close: "18:00", breakStart: "12:00", breakEnd: "13:00", status: "aberto" },
    { day: "terca", label: "Terça", open: "08:00", close: "18:00", breakStart: "12:00", breakEnd: "13:00", status: "aberto" },
    { day: "quarta", label: "Quarta", open: "08:00", close: "18:00", breakStart: "12:00", breakEnd: "13:00", status: "aberto" },
    { day: "quinta", label: "Quinta", open: "08:00", close: "18:00", breakStart: "12:00", breakEnd: "13:00", status: "aberto" },
    { day: "sexta", label: "Sexta", open: "08:00", close: "18:00", breakStart: "12:00", breakEnd: "13:00", status: "aberto" },
    { day: "sabado", label: "Sábado", open: "08:00", close: "13:00", breakStart: "", breakEnd: "", status: "aberto" },
    { day: "domingo", label: "Domingo", open: "", close: "", breakStart: "", breakEnd: "", status: "fechado" },
  ],
  bancarios: {
    banco: "341 - Itaú Unibanco",
    agencia: "1234",
    conta: "56789-0",
    tipo: "Corrente",
    pix: "12.345.678/0001-90",
    titular: "Sorriso Premium Odontologia Ltda",
    documento: "12.345.678/0001-90",
  },
  financeiros: {
    moeda: "BRL",
    diasVencimento: 7,
    juros: "1%",
    multa: "2%",
    descontoMaximo: "10%",
    taxaAdministrativa: "0%",
    contaPadrao: "Conta Corrente Itaú",
    centroCustoPadrao: "Clínica - Operacional",
  },
  fiscais: {
    regimeTributario: "Simples Nacional",
    cnae: "8630-5/03",
    inscricaoMunicipal: "12345678",
    codigoIbge: "3550308",
    codigoMunicipio: "7107",
    emissorNf: "Nacional",
    serie: "1",
    proximoNumero: "158",
  },
  convenios: [
    {
      id: "cv1",
      name: "Bradesco Dental",
      code: "BRAD-01",
      contact: "Ana Paula",
      phone: "(11) 4004-0000",
      paymentTermDays: 30,
      status: "ativo",
    },
    {
      id: "cv2",
      name: "OdontoPrev",
      code: "OP-22",
      contact: "Ricardo Lima",
      phone: "(11) 3003-3003",
      paymentTermDays: 45,
      status: "ativo",
    },
  ],
  identidade: {
    logoPrincipal: "",
    logoBranca: "",
    logoEscura: "",
    favicon: "",
    marcaDagua: "",
    corPrimaria: "#2563eb",
    corSecundaria: "#0b1b34",
    corDestaque: "#3b82f6",
    fonte: "Inter",
  },
  documentos: {
    cabecalho: "Clínica Sorriso Premium — Excelência em Odontologia",
    rodape: "Av. Paulista, 1000 — São Paulo/SP | (11) 3456-7890",
    termosUso: "Ao utilizar nossos serviços, o paciente concorda com as políticas da clínica.",
    textoOrcamentos: "Orçamento válido por 30 dias. Valores sujeitos a reavaliação clínica.",
    textoRecibos: "Recebemos o valor acima referente aos serviços odontológicos descritos.",
    textoReceitas: "Uso contínuo conforme orientação do cirurgião-dentista responsável.",
    textoAtestados: "Atesto para os devidos fins que o paciente esteve sob cuidados nesta clínica.",
    modeloContratos: "Modelo padrão de contrato de prestação de serviços odontológicos.",
  },
  lgpd: {
    politicaPrivacidade:
      "Tratamos dados pessoais conforme a LGPD, exclusivamente para fins assistenciais e administrativos.",
    consentimento:
      "O paciente autoriza o tratamento de dados necessários à execução do plano terapêutico.",
    compartilhamento:
      "Dados poderão ser compartilhados com laboratórios e operadoras apenas quando necessário.",
    tempoArmazenamento: "5 anos após o último atendimento",
    dadosSensiveis:
      "Dados de saúde são tratados com acesso restrito à equipe clínica autorizada.",
    retencaoProntuarios: "Prontuários mantidos pelo prazo mínimo legal aplicável.",
  },
  configuracoes: {
    fusoHorario: "America/Sao_Paulo",
    formatoData: "DD/MM/AAAA",
    formatoMoeda: "R$ #.###,##",
    idioma: "pt-BR",
    backupAutomatico: true,
    tema: "claro",
    notificacoes: true,
    assinaturaEletronica: true,
    autoSave: false,
  },
  resumo: {
    plano: "Premium",
    status: "ativa",
    espacoUsadoGb: 2.4,
    espacoTotalGb: 10,
    pacientes: 1284,
    profissionais: 12,
    consultas: 4860,
    ultimoBackup: "26/07/2026 03:00",
    validadeLicenca: "15/07/2027",
  },
};
