import type { ContasAPagarData, PayableAccount } from "@/lib/contas-a-pagar-types";

const accounts: PayableAccount[] = [
  {
    id: "p1",
    dueDate: "2026-07-26",
    dueLabel: "26/07/2026",
    supplier: "Dental Lab SP",
    description: "Próteses e modelos do mês",
    category: "Laboratório",
    costCenter: "Clínica",
    bankAccount: "Itaú - 1234",
    paymentMethod: "PIX",
    document: "BOL-88421",
    invoiceNumber: "NF 4412",
    amount: 2450,
    paidAmount: 0,
    balance: 2450,
    status: "vencido",
    responsible: "Financeiro",
    notes: "Urgente",
    attachments: 2,
  },
  {
    id: "p2",
    dueDate: "2026-07-26",
    dueLabel: "26/07/2026",
    supplier: "Claro Empresas",
    description: "Internet clínica",
    category: "Internet",
    costCenter: "Administrativo",
    bankAccount: "Bradesco - 9988",
    paymentMethod: "Boleto",
    document: "BOL-11209",
    invoiceNumber: "NF 2201",
    amount: 389,
    paidAmount: 0,
    balance: 389,
    status: "vencido",
    responsible: "Administrativo",
    notes: "",
    attachments: 1,
  },
  {
    id: "p3",
    dueDate: "2026-07-27",
    dueLabel: "27/07/2026",
    supplier: "Imobiliária Paulista",
    description: "Aluguel da sala comercial",
    category: "Aluguel",
    costCenter: "Administrativo",
    bankAccount: "Itaú - 1234",
    paymentMethod: "Transferência",
    document: "DOC-9001",
    invoiceNumber: "—",
    amount: 8500,
    paidAmount: 0,
    balance: 8500,
    status: "em_aberto",
    responsible: "Financeiro",
    notes: "Recorrente",
    attachments: 0,
  },
  {
    id: "p4",
    dueDate: "2026-07-28",
    dueLabel: "28/07/2026",
    supplier: "Enel SP",
    description: "Energia elétrica",
    category: "Energia",
    costCenter: "Operacional",
    bankAccount: "Santander - 5542",
    paymentMethod: "Boleto",
    document: "BOL-33410",
    invoiceNumber: "NF 778",
    amount: 1240,
    paidAmount: 0,
    balance: 1240,
    status: "em_aberto",
    responsible: "Financeiro",
    notes: "",
    attachments: 1,
  },
  {
    id: "p5",
    dueDate: "2026-07-30",
    dueLabel: "30/07/2026",
    supplier: "Materiais Odonto Plus",
    description: "Resinas e kits descartáveis",
    category: "Material Odontológico",
    costCenter: "Estoque",
    bankAccount: "Itaú - 1234",
    paymentMethod: "Cartão",
    document: "NF-556",
    invoiceNumber: "NF 556",
    amount: 3180,
    paidAmount: 1000,
    balance: 2180,
    status: "parcial",
    responsible: "Estoque",
    notes: "Parcela 1/3",
    attachments: 3,
  },
  {
    id: "p6",
    dueDate: "2026-08-05",
    dueLabel: "05/08/2026",
    supplier: "Folha Clínica",
    description: "Salários equipe clínica",
    category: "Salários",
    costCenter: "RH",
    bankAccount: "Itaú - 1234",
    paymentMethod: "Transferência",
    document: "FOL-07",
    invoiceNumber: "—",
    amount: 42000,
    paidAmount: 0,
    balance: 42000,
    status: "agendado",
    responsible: "RH",
    notes: "",
    attachments: 0,
  },
  {
    id: "p7",
    dueDate: "2026-07-10",
    dueLabel: "10/07/2026",
    supplier: "Software Odonto Cloud",
    description: "Assinatura mensal SaaS",
    category: "Software",
    costCenter: "TI",
    bankAccount: "Bradesco - 9988",
    paymentMethod: "Cartão",
    document: "ASS-07",
    invoiceNumber: "NF 91",
    amount: 690,
    paidAmount: 690,
    balance: 0,
    status: "pago",
    responsible: "TI",
    notes: "",
    attachments: 1,
  },
  {
    id: "p8",
    dueDate: "2026-07-15",
    dueLabel: "15/07/2026",
    supplier: "Agência Smile Ads",
    description: "Campanha Google Ads",
    category: "Marketing",
    costCenter: "Marketing",
    bankAccount: "Santander - 5542",
    paymentMethod: "PIX",
    document: "MKT-441",
    invoiceNumber: "NF 301",
    amount: 2200,
    paidAmount: 2200,
    balance: 0,
    status: "pago",
    responsible: "Marketing",
    notes: "",
    attachments: 0,
  },
  {
    id: "p9",
    dueDate: "2026-07-20",
    dueLabel: "20/07/2026",
    supplier: "Sabesp",
    description: "Água e esgoto",
    category: "Água",
    costCenter: "Operacional",
    bankAccount: "Itaú - 1234",
    paymentMethod: "Boleto",
    document: "BOL-7781",
    invoiceNumber: "NF 120",
    amount: 310,
    paidAmount: 0,
    balance: 310,
    status: "vencido",
    responsible: "Financeiro",
    notes: "",
    attachments: 1,
  },
  {
    id: "p10",
    dueDate: "2026-07-29",
    dueLabel: "29/07/2026",
    supplier: "Contabilidade Alpha",
    description: "Honorários contábeis",
    category: "Impostos",
    costCenter: "Administrativo",
    bankAccount: "Bradesco - 9988",
    paymentMethod: "PIX",
    document: "CONT-07",
    invoiceNumber: "NF 88",
    amount: 1800,
    paidAmount: 0,
    balance: 1800,
    status: "em_aberto",
    responsible: "Financeiro",
    notes: "",
    attachments: 2,
  },
];

function buildCalendar(): ContasAPagarData["calendar"] {
  const cells: ContasAPagarData["calendar"] = [];
  // July 2026 starts on Wednesday (day 1 = Wed)
  const firstWeekday = 3; // 0=Sun
  for (let i = 0; i < firstWeekday; i++) {
    cells.push({ date: "", day: 0, total: 0, tone: "vazio", count: 0 });
  }
  const byDay = new Map<number, { total: number; count: number; tone: ContasAPagarData["calendar"][0]["tone"] }>();
  for (const a of accounts) {
    if (!a.dueDate.startsWith("2026-07")) continue;
    const day = Number(a.dueDate.slice(8, 10));
    const prev = byDay.get(day) || { total: 0, count: 0, tone: "neutro" as const };
    prev.total += a.balance > 0 ? a.balance : a.amount;
    prev.count += 1;
    if (a.status === "vencido") prev.tone = "atraso";
    else if (a.dueDate === "2026-07-26" && prev.tone !== "atraso") prev.tone = "hoje";
    else if (a.status === "pago" && prev.tone === "neutro") prev.tone = "pago";
    else if (a.status !== "pago" && prev.tone === "neutro") prev.tone = "proximo";
    byDay.set(day, prev);
  }
  for (let day = 1; day <= 31; day++) {
    const info = byDay.get(day);
    cells.push({
      date: `2026-07-${String(day).padStart(2, "0")}`,
      day,
      total: info?.total || 0,
      count: info?.count || 0,
      tone: info?.tone || "neutro",
    });
  }
  return cells;
}

export const CONTAS_A_PAGAR_MOCK: ContasAPagarData = {
  kpis: [
    {
      id: "aberto",
      label: "Total em aberto",
      value: "R$ 58.420,00",
      hint: "28 contas",
      progress: 32,
      tone: "amber",
    },
    {
      id: "pago",
      label: "Total pago",
      value: "R$ 142.850,00",
      hint: "56 contas",
      progress: 68,
      tone: "green",
    },
    {
      id: "hoje",
      label: "Vencendo hoje",
      value: "7 contas",
      hint: "R$ 8.750,00",
      tone: "amber",
    },
    {
      id: "vencidos",
      label: "Vencidas",
      value: "11 contas",
      hint: "R$ 12.350,00",
      tone: "red",
    },
    {
      id: "7dias",
      label: "Próximos 7 dias",
      value: "R$ 16.780,00",
      hint: "14 contas",
      tone: "blue",
    },
    {
      id: "mes",
      label: "Total do mês",
      value: "R$ 201.270,00",
      hint: "84 contas lançadas",
      tone: "violet",
    },
  ],
  accounts,
  calendar: buildCalendar(),
  calendarMonthLabel: "Julho 2026",
  categoryShare: [
    { name: "Aluguel", percent: 28, color: "#2563eb" },
    { name: "Laboratório", percent: 18, color: "#7c3aed" },
    { name: "Material Odontológico", percent: 15, color: "#10b981" },
    { name: "Salários", percent: 12, color: "#0ea5e9" },
    { name: "Impostos", percent: 8, color: "#f59e0b" },
    { name: "Software", percent: 6, color: "#6366f1" },
    { name: "Marketing", percent: 5, color: "#ec4899" },
    { name: "Outros", percent: 8, color: "#64748b" },
  ],
  statusShare: [
    { name: "Pago", percent: 66, color: "#10b981" },
    { name: "Em aberto", percent: 21, color: "#f59e0b" },
    { name: "Vencido", percent: 13, color: "#f43f5e" },
  ],
  outflowMonthly: [
    { label: "Jan", value: 148000 },
    { label: "Fev", value: 152000 },
    { label: "Mar", value: 161000 },
    { label: "Abr", value: 158000 },
    { label: "Mai", value: 172000 },
    { label: "Jun", value: 168000 },
    { label: "Jul", value: 201270 },
  ],
  upcoming: [
    { id: "u1", when: "Hoje", label: "Dental Lab SP + Claro", amount: 2839, count: 2 },
    { id: "u2", when: "Amanhã", label: "Imobiliária Paulista", amount: 8500, count: 1 },
    { id: "u3", when: "Terça", label: "Enel SP", amount: 1240, count: 1 },
    { id: "u4", when: "Quarta", label: "Contabilidade Alpha", amount: 1800, count: 1 },
    { id: "u5", when: "Quinta", label: "Materiais Odonto Plus", amount: 2180, count: 1 },
  ],
  alerts: [
    {
      id: "a1",
      title: "Boletos vencidos",
      detail: "11 contas vencidas (R$ 12.350)",
      priority: "alta",
    },
    {
      id: "a2",
      title: "Boletos próximos do vencimento",
      detail: "7 contas vencem hoje",
      priority: "media",
    },
    {
      id: "a3",
      title: "Contas duplicadas",
      detail: "3 boletos com possível duplicidade",
      priority: "media",
    },
    {
      id: "a4",
      title: "Notas fiscais pendentes",
      detail: "2 NFs aguardando upload",
      priority: "baixa",
    },
    {
      id: "a5",
      title: "Recorrentes sem lançamento",
      detail: "Água e Internet sem lançamento de agosto",
      priority: "alta",
    },
  ],
  summary: {
    totalAberto: 58420,
    totalPago: 142850,
    emAtraso: 12350,
    previsao: 16780,
    maiorFornecedor: "Imobiliária Paulista",
    categoriaTop: "Aluguel",
    ultimosPagamentos: [
      { id: "lp1", label: "Software Odonto Cloud", amount: 690, date: "10/07/2026" },
      { id: "lp2", label: "Agência Smile Ads", amount: 2200, date: "15/07/2026" },
      { id: "lp3", label: "Materiais Odonto Plus", amount: 1000, date: "22/07/2026" },
    ],
  },
  filterOptions: {
    suppliers: [
      "Todos",
      "Dental Lab SP",
      "Claro Empresas",
      "Imobiliária Paulista",
      "Enel SP",
      "Materiais Odonto Plus",
    ],
    categories: [
      "Todas",
      "Aluguel",
      "Energia",
      "Água",
      "Internet",
      "Salários",
      "Impostos",
      "Material Odontológico",
      "Laboratório",
      "Marketing",
      "Software",
      "Manutenção",
      "Outros",
    ],
    costCenters: ["Todos", "Clínica", "Administrativo", "Operacional", "Estoque", "RH", "TI", "Marketing"],
    bankAccounts: ["Todas", "Itaú - 1234", "Bradesco - 9988", "Santander - 5542"],
    paymentMethods: ["Todas", "PIX", "Boleto", "Cartão", "Transferência", "Dinheiro", "Cheque"],
    statuses: ["Todos", "Pago", "Em aberto", "Parcial", "Vencido", "Cancelado", "Agendado"],
    responsibles: ["Todos", "Financeiro", "Administrativo", "Estoque", "RH", "TI", "Marketing"],
  },
};
