import type { ContasAReceberData, ReceivableInstallment } from "@/lib/contas-a-receber-types";

const installments: ReceivableInstallment[] = [
  {
    id: "r1",
    patient: "Maria Silva",
    cpf: "123.456.789-00",
    phone: "(11) 98888-1111",
    budgetNumber: "ORC-1042",
    procedure: "Clareamento",
    professional: "Dra. Ana",
    convenio: "Particular",
    installment: 1,
    totalInstallments: 1,
    dueDate: "2026-07-26",
    dueLabel: "26/07/2026",
    amount: 850,
    receivedAmount: 0,
    balance: 850,
    paymentMethod: "PIX",
    bankAccount: "Itaú - 1234",
    status: "vencido",
    notes: "",
  },
  {
    id: "r2",
    patient: "João Pedro",
    cpf: "987.654.321-00",
    phone: "(11) 97777-2222",
    budgetNumber: "ORC-1038",
    procedure: "Implante",
    professional: "Dr. Carlos",
    convenio: "Particular",
    installment: 2,
    totalInstallments: 3,
    dueDate: "2026-07-26",
    dueLabel: "26/07/2026",
    amount: 1400,
    receivedAmount: 0,
    balance: 1400,
    paymentMethod: "Cartão Crédito",
    bankAccount: "Santander - 5542",
    status: "vencido",
    notes: "Parcela 2/3",
  },
  {
    id: "r3",
    patient: "Ana Costa",
    cpf: "111.222.333-44",
    phone: "(11) 96666-3333",
    budgetNumber: "ORC-1050",
    procedure: "Limpeza",
    professional: "Dra. Ana",
    convenio: "Unimed",
    installment: 1,
    totalInstallments: 1,
    dueDate: "2026-07-27",
    dueLabel: "27/07/2026",
    amount: 280,
    receivedAmount: 0,
    balance: 280,
    paymentMethod: "Convênio",
    bankAccount: "Bradesco - 9988",
    status: "em_aberto",
    notes: "",
  },
  {
    id: "r4",
    patient: "Pedro Lima",
    cpf: "555.666.777-88",
    phone: "(11) 95555-4444",
    budgetNumber: "ORC-1045",
    procedure: "Canal",
    professional: "Dr. Rafael",
    convenio: "Particular",
    installment: 1,
    totalInstallments: 2,
    dueDate: "2026-07-28",
    dueLabel: "28/07/2026",
    amount: 600,
    receivedAmount: 200,
    balance: 400,
    paymentMethod: "PIX",
    bankAccount: "Itaú - 1234",
    status: "parcial",
    notes: "Recebido parcial",
  },
  {
    id: "r5",
    patient: "Carla Mendes",
    cpf: "222.333.444-55",
    phone: "(11) 94444-5555",
    budgetNumber: "ORC-1030",
    procedure: "Ortodontia",
    professional: "Dra. Ana",
    convenio: "Amil",
    installment: 3,
    totalInstallments: 12,
    dueDate: "2026-07-30",
    dueLabel: "30/07/2026",
    amount: 450,
    receivedAmount: 0,
    balance: 450,
    paymentMethod: "Boleto",
    bankAccount: "Itaú - 1234",
    status: "em_aberto",
    notes: "",
  },
  {
    id: "r6",
    patient: "Bruno Alves",
    cpf: "333.444.555-66",
    phone: "(11) 93333-6666",
    budgetNumber: "ORC-1022",
    procedure: "Prótese",
    professional: "Dr. Carlos",
    convenio: "Particular",
    installment: 1,
    totalInstallments: 4,
    dueDate: "2026-07-15",
    dueLabel: "15/07/2026",
    amount: 1200,
    receivedAmount: 1200,
    balance: 0,
    paymentMethod: "Transferência",
    bankAccount: "Bradesco - 9988",
    status: "pago",
    notes: "",
  },
  {
    id: "r7",
    patient: "Fernanda Dias",
    cpf: "444.555.666-77",
    phone: "(11) 92222-7777",
    budgetNumber: "ORC-1048",
    procedure: "Restauração",
    professional: "Dr. Rafael",
    convenio: "Bradesco Dental",
    installment: 1,
    totalInstallments: 1,
    dueDate: "2026-07-20",
    dueLabel: "20/07/2026",
    amount: 380,
    receivedAmount: 0,
    balance: 380,
    paymentMethod: "Convênio",
    bankAccount: "Santander - 5542",
    status: "vencido",
    notes: "Inadimplente",
  },
  {
    id: "r8",
    patient: "Lucas Rocha",
    cpf: "666.777.888-99",
    phone: "(11) 91111-8888",
    budgetNumber: "ORC-1055",
    procedure: "Extração",
    professional: "Dr. Carlos",
    convenio: "Particular",
    installment: 1,
    totalInstallments: 1,
    dueDate: "2026-08-05",
    dueLabel: "05/08/2026",
    amount: 520,
    receivedAmount: 0,
    balance: 520,
    paymentMethod: "Dinheiro",
    bankAccount: "Itaú - 1234",
    status: "negociado",
    notes: "Acordo verbal",
  },
];

function buildCalendar(): ContasAReceberData["calendar"] {
  const cells: ContasAReceberData["calendar"] = [];
  const firstWeekday = 3;
  for (let i = 0; i < firstWeekday; i++) {
    cells.push({ date: "", day: 0, total: 0, tone: "vazio", count: 0 });
  }
  const byDay = new Map<
    number,
    { total: number; count: number; tone: ContasAReceberData["calendar"][0]["tone"] }
  >();
  for (const a of installments) {
    if (!a.dueDate.startsWith("2026-07")) continue;
    const day = Number(a.dueDate.slice(8, 10));
    const prev = byDay.get(day) || { total: 0, count: 0, tone: "neutro" as const };
    prev.total += a.balance > 0 ? a.balance : a.amount;
    prev.count += 1;
    if (a.status === "vencido") prev.tone = "atraso";
    else if (a.dueDate === "2026-07-26" && prev.tone !== "atraso") prev.tone = "hoje";
    else if (a.status === "pago" && prev.tone === "neutro") prev.tone = "pago";
    else if (a.status !== "pago" && prev.tone === "neutro") prev.tone = "proximo";
    byDay.set(day, prev);
  }
  for (let day = 1; day <= 31; day++) {
    const info = byDay.get(day);
    cells.push({
      date: `2026-07-${String(day).padStart(2, "0")}`,
      day,
      total: info?.total || 0,
      count: info?.count || 0,
      tone: info?.tone || "neutro",
    });
  }
  return cells;
}

export const CONTAS_A_RECEBER_MOCK: ContasAReceberData = {
  kpis: [
    {
      id: "receber",
      label: "Total a Receber",
      value: "R$ 74.320,00",
      hint: "Em aberto",
      tone: "amber",
    },
    {
      id: "recebido",
      label: "Recebido no mês",
      value: "R$ 128.540,00",
      delta: 18.6,
      tone: "green",
    },
    {
      id: "previstos",
      label: "Recebimentos previstos",
      value: "R$ 32.450,00",
      hint: "Próximos 30 dias",
      tone: "blue",
    },
    {
      id: "vencidas",
      label: "Parcelas vencidas",
      value: "18 parcelas",
      hint: "R$ 12.350,00",
      tone: "red",
    },
    {
      id: "hoje",
      label: "Vencendo hoje",
      value: "6 parcelas",
      hint: "R$ 4.280,00",
      tone: "amber",
    },
    {
      id: "inadimplencia",
      label: "Inadimplência",
      value: "8 pacientes",
      hint: "R$ 9.640,00",
      tone: "red",
    },
    {
      id: "ticket",
      label: "Ticket Médio",
      value: "R$ 642,00",
      hint: "Por paciente",
      tone: "violet",
    },
    {
      id: "orcamentos",
      label: "Orçamentos aprovados",
      value: "42",
      hint: "R$ 186.900,00",
      tone: "slate",
    },
  ],
  installments,
  calendar: buildCalendar(),
  calendarMonthLabel: "Julho 2026",
  paymentShare: [
    { name: "PIX", percent: 38, color: "#10b981" },
    { name: "Cartão Crédito", percent: 28, color: "#2563eb" },
    { name: "Cartão Débito", percent: 12, color: "#6366f1" },
    { name: "Dinheiro", percent: 8, color: "#f59e0b" },
    { name: "Transferência", percent: 6, color: "#0ea5e9" },
    { name: "Boleto", percent: 5, color: "#64748b" },
    { name: "Convênio", percent: 3, color: "#ec4899" },
  ],
  convenios: [
    { id: "c1", name: "Unimed", guides: 28, forecast: 12450, received: 8200, balance: 4250 },
    { id: "c2", name: "Amil", guides: 19, forecast: 8920, received: 6100, balance: 2820 },
    { id: "c3", name: "Bradesco Dental", guides: 14, forecast: 6780, received: 4500, balance: 2280 },
    { id: "c4", name: "Particular", guides: 62, forecast: 46170, received: 38900, balance: 7270 },
  ],
  upcoming: [
    { id: "u1", when: "Hoje", label: "Maria Silva + João Pedro", amount: 2250, count: 2 },
    { id: "u2", when: "Amanhã", label: "Ana Costa — Limpeza", amount: 280, count: 1 },
    { id: "u3", when: "Terça", label: "Pedro Lima — Canal", amount: 400, count: 1 },
    { id: "u4", when: "Quinta", label: "Carla Mendes — Ortodontia", amount: 450, count: 1 },
  ],
  alerts: [
    {
      id: "a1",
      title: "Parcelas vencidas",
      detail: "18 parcelas em atraso (R$ 12.350)",
      priority: "alta",
    },
    {
      id: "a2",
      title: "Pacientes inadimplentes",
      detail: "8 pacientes com saldo em aberto",
      priority: "alta",
    },
    {
      id: "a3",
      title: "Cobranças pendentes",
      detail: "5 links de pagamento aguardando",
      priority: "media",
    },
    {
      id: "a4",
      title: "Boletos vencidos",
      detail: "3 boletos sem baixa",
      priority: "media",
    },
    {
      id: "a5",
      title: "PIX pendentes",
      detail: "4 cobranças PIX não compensadas",
      priority: "baixa",
    },
    {
      id: "a6",
      title: "Convênios em atraso",
      detail: "1 operadora com repasse atrasado",
      priority: "media",
    },
  ],
  goal: { current: 128540, target: 150000 },
  summary: {
    totalAberto: 74320,
    totalRecebido: 128540,
    previstos: 32450,
    vencidos: 12350,
    maiorPagador: "João Pedro",
    convenioTop: "Particular",
    procedimentoTop: "Implante",
    receitaMes: 128540,
  },
  filterOptions: {
    statuses: ["Todos", "Pago", "Recebido Parcial", "Em Aberto", "Vencido", "Cancelado", "Negociado"],
    paymentMethods: [
      "Todas",
      "PIX",
      "Cartão Crédito",
      "Cartão Débito",
      "Dinheiro",
      "Transferência",
      "Boleto",
      "Convênio",
    ],
    professionals: ["Todos", "Dra. Ana", "Dr. Carlos", "Dr. Rafael"],
    convenios: ["Todos", "Particular", "Unimed", "Amil", "Bradesco Dental"],
    procedures: ["Todos", "Clareamento", "Implante", "Limpeza", "Canal", "Ortodontia", "Prótese"],
    categories: ["Todas", "Estética", "Cirurgia", "Clínica", "Ortodontia"],
    responsibles: ["Todos", "Financeiro", "Recepção", "Dra. Ana"],
    bankAccounts: ["Todas", "Itaú - 1234", "Bradesco - 9988", "Santander - 5542"],
  },
};
