export const dashboardMock = {
  periodLabel: "Julho / 2026",
  kpis: [
    {
      id: "faturamento",
      label: "Faturamento (mês)",
      value: "R$ 87.450,00",
      growth: 12.5,
      tone: "blue" as const,
      sparkline: [42, 48, 45, 52, 58, 55, 62, 68, 65, 72, 78, 87],
    },
    {
      id: "recebimentos",
      label: "Recebimentos (mês)",
      value: "R$ 76.210,00",
      growth: 14.2,
      tone: "green" as const,
      sparkline: [38, 40, 44, 42, 50, 54, 52, 60, 64, 70, 72, 76],
    },
    {
      id: "consultas",
      label: "Consultas (mês)",
      value: "128",
      growth: 10.8,
      tone: "purple" as const,
      sparkline: [80, 85, 82, 90, 95, 100, 98, 110, 115, 118, 122, 128],
    },
    {
      id: "pacientes",
      label: "Novos pacientes",
      value: "32",
      growth: 14.5,
      tone: "orange" as const,
      sparkline: [18, 20, 19, 22, 24, 23, 26, 28, 27, 29, 30, 32],
    },
  ],
  agendaHoje: [
    {
      id: "1",
      time: "08:30",
      patient: "Maria Silva",
      initials: "MS",
      procedure: "Limpeza Dental",
      status: "confirmado" as const,
    },
    {
      id: "2",
      time: "09:15",
      patient: "João Pedro",
      initials: "JP",
      procedure: "Restauração",
      status: "em_andamento" as const,
    },
    {
      id: "3",
      time: "10:00",
      patient: "Ana Costa",
      initials: "AC",
      procedure: "Avaliação",
      status: "pendente" as const,
    },
    {
      id: "4",
      time: "11:30",
      patient: "Carlos Lima",
      initials: "CL",
      procedure: "Clareamento",
      status: "confirmado" as const,
    },
    {
      id: "5",
      time: "14:00",
      patient: "Fernanda Souza",
      initials: "FS",
      procedure: "Canal",
      status: "confirmado" as const,
    },
  ],
  faturamento6Meses: [
    { month: "Jan", value: 52 },
    { month: "Fev", value: 58 },
    { month: "Mar", value: 61 },
    { month: "Abr", value: 55 },
    { month: "Mai", value: 72 },
    { month: "Jun", value: 87 },
  ],
  procedimentos: [
    { name: "Clareamento", percent: 38, color: "#6366f1" },
    { name: "Restauração", percent: 24, color: "#3b82f6" },
    { name: "Limpeza", percent: 20, color: "#22c55e" },
    { name: "Canal", percent: 10, color: "#f59e0b" },
    { name: "Extração", percent: 8, color: "#ef4444" },
  ],
  procedimentosTotal: 256,
  odontoStats: [
    { label: "Dentes tratados", value: 186 },
    { label: "Tratamentos ativos", value: 74 },
    { label: "Tratamentos concluídos", value: 112 },
    { label: "Pendências", value: 48 },
  ],
  /** status: saudavel | concluido | andamento | indicado */
  odontogramUpper: [
    "saudavel",
    "concluido",
    "saudavel",
    "andamento",
    "saudavel",
    "indicado",
    "saudavel",
    "concluido",
    "saudavel",
    "saudavel",
    "andamento",
    "saudavel",
    "indicado",
    "saudavel",
    "concluido",
    "saudavel",
  ],
  odontogramLower: [
    "saudavel",
    "andamento",
    "saudavel",
    "saudavel",
    "concluido",
    "saudavel",
    "indicado",
    "saudavel",
    "saudavel",
    "concluido",
    "saudavel",
    "andamento",
    "saudavel",
    "saudavel",
    "indicado",
    "saudavel",
  ],
  contasReceber: [
    { id: "1", patient: "Maria Silva", initials: "MS", date: "05/07/2026", amount: "R$ 850,00", status: "a_vencer" as const },
    { id: "2", patient: "João Pedro", initials: "JP", date: "28/06/2026", amount: "R$ 1.200,00", status: "atrasado" as const },
    { id: "3", patient: "Ana Costa", initials: "AC", date: "10/07/2026", amount: "R$ 450,00", status: "a_vencer" as const },
    { id: "4", patient: "Carlos Lima", initials: "CL", date: "22/06/2026", amount: "R$ 980,00", status: "atrasado" as const },
    { id: "5", patient: "Fernanda Souza", initials: "FS", date: "12/07/2026", amount: "R$ 320,00", status: "a_vencer" as const },
  ],
  resumoFinanceiro: {
    receitas: "R$ 76.210,00",
    despesas: "R$ 24.980,00",
    lucroLiquido: "R$ 51.230,00",
    margem: "67,2%",
  },
  comissoes: [
    { id: "1", name: "Dr. Carlos Mendes", initials: "CM", billed: "R$ 28.400", commission: "R$ 8.520", percent: 78 },
    { id: "2", name: "Dra. Juliana Reis", initials: "JR", billed: "R$ 22.100", commission: "R$ 6.630", percent: 62 },
    { id: "3", name: "Dr. Pedro Alves", initials: "PA", billed: "R$ 18.750", commission: "R$ 5.625", percent: 54 },
    { id: "4", name: "Dra. Sofia Martins", initials: "SM", billed: "R$ 12.200", commission: "R$ 3.660", percent: 38 },
  ],
  alertas: [
    { id: "1", text: "2 orçamentos aguardando aprovação", tone: "blue" as const },
    { id: "2", text: "5 pagamentos vencidos", tone: "red" as const },
    { id: "3", text: "2 itens com estoque baixo", tone: "orange" as const },
    { id: "4", text: "12 confirmações de consulta pendentes", tone: "purple" as const },
  ],
  atividades: [
    { id: "1", text: "Orçamento aprovado por Maria Silva", time: "Há 12 min", type: "orcamento" },
    { id: "2", text: "Consulta confirmada — João Pedro", time: "Há 28 min", type: "agenda" },
    { id: "3", text: "Recebimento PIX de R$ 850,00", time: "Há 1 h", type: "financeiro" },
    { id: "4", text: "Novo paciente cadastrado: Ana Costa", time: "Há 2 h", type: "paciente" },
    { id: "5", text: "Tratamento concluído no dente 16", time: "Há 3 h", type: "clinico" },
  ],
};
