import type { FinanceiroGeralData } from "@/lib/financeiro-geral-types";

export const FINANCEIRO_GERAL_MOCK: FinanceiroGeralData = {
  kpis: [
    {
      id: "receitas",
      label: "Receitas do Mês",
      value: "R$ 128.540,00",
      delta: 18.6,
      sparkline: [72, 78, 81, 86, 90, 95, 102, 110, 118, 128],
      tone: "green",
    },
    {
      id: "despesas",
      label: "Despesas do Mês",
      value: "R$ 42.850,00",
      delta: 8.2,
      sparkline: [30, 32, 31, 34, 36, 38, 37, 40, 41, 43],
      tone: "red",
    },
    {
      id: "lucro",
      label: "Lucro Líquido",
      value: "R$ 85.690,00",
      delta: 23.4,
      sparkline: [42, 46, 50, 52, 54, 57, 65, 70, 77, 86],
      tone: "blue",
    },
    {
      id: "receber",
      label: "Contas a Receber",
      value: "36",
      hint: "Total R$ 74.320,00",
      tone: "amber",
    },
    {
      id: "pagar",
      label: "Contas a Pagar",
      value: "18",
      hint: "Total R$ 23.650,00",
      tone: "violet",
    },
    {
      id: "caixa",
      label: "Caixa Atual",
      value: "R$ 58.420,00",
      hint: "Saldo disponível",
      tone: "slate",
    },
    {
      id: "convenios",
      label: "Convênios a Receber",
      value: "R$ 32.450,00",
      hint: "Valor previsto",
      tone: "blue",
    },
    {
      id: "fluxo",
      label: "Fluxo de Caixa",
      value: "R$ 112.750,00",
      hint: "Saldo previsto",
      tone: "green",
    },
  ],
  cashflowDaily: [
    { label: "01", receitas: 4200, despesas: 1800, lucro: 2400 },
    { label: "05", receitas: 5100, despesas: 2100, lucro: 3000 },
    { label: "10", receitas: 4800, despesas: 1900, lucro: 2900 },
    { label: "15", receitas: 6200, despesas: 2400, lucro: 3800 },
    { label: "20", receitas: 5800, despesas: 2200, lucro: 3600 },
    { label: "25", receitas: 7100, despesas: 2600, lucro: 4500 },
    { label: "30", receitas: 6900, despesas: 2500, lucro: 4400 },
  ],
  cashflowWeekly: [
    { label: "Sem 01", receitas: 22000, despesas: 8200, lucro: 13800 },
    { label: "Sem 02", receitas: 24500, despesas: 9100, lucro: 15400 },
    { label: "Sem 03", receitas: 26800, despesas: 8800, lucro: 18000 },
    { label: "Sem 04", receitas: 29200, despesas: 9600, lucro: 19600 },
    { label: "Sem 05", receitas: 26040, despesas: 7150, lucro: 18890 },
  ],
  cashflowMonthly: [
    { label: "Jan", receitas: 98000, despesas: 36000, lucro: 62000 },
    { label: "Fev", receitas: 102000, despesas: 38000, lucro: 64000 },
    { label: "Mar", receitas: 110000, despesas: 39000, lucro: 71000 },
    { label: "Abr", receitas: 118000, despesas: 41000, lucro: 77000 },
    { label: "Mai", receitas: 128540, despesas: 42850, lucro: 85690 },
    { label: "Jun", receitas: 121000, despesas: 40000, lucro: 81000 },
  ],
  cashflowYearly: [
    { label: "2022", receitas: 980000, despesas: 420000, lucro: 560000 },
    { label: "2023", receitas: 1120000, despesas: 460000, lucro: 660000 },
    { label: "2024", receitas: 1280000, despesas: 510000, lucro: 770000 },
    { label: "2025", receitas: 1390000, despesas: 540000, lucro: 850000 },
    { label: "2026", receitas: 760000, despesas: 280000, lucro: 480000 },
  ],
  incomeExpenseBars: [
    { label: "Sem 01", receitas: 22000, despesas: 8200 },
    { label: "Sem 02", receitas: 24500, despesas: 9100 },
    { label: "Sem 03", receitas: 26800, despesas: 8800 },
    { label: "Sem 04", receitas: 29200, despesas: 9600 },
    { label: "Sem 05", receitas: 26040, despesas: 7150 },
  ],
  bankAccounts: [
    {
      id: "b1",
      bank: "Itaú Unibanco",
      account: "CC 12345-6",
      balance: 28450,
      updatedAt: "Hoje, 14:32",
    },
    {
      id: "b2",
      bank: "Bradesco",
      account: "CC 99887-1",
      balance: 16200,
      updatedAt: "Hoje, 09:10",
    },
    {
      id: "b3",
      bank: "Santander",
      account: "CC 55421-0",
      balance: 13770,
      updatedAt: "Ontem, 18:40",
    },
  ],
  paymentMethods: [
    { name: "PIX", percent: 38, color: "#10b981" },
    { name: "Cartão Crédito", percent: 28, color: "#2563eb" },
    { name: "Cartão Débito", percent: 14, color: "#6366f1" },
    { name: "Dinheiro", percent: 8, color: "#f59e0b" },
    { name: "Transferência", percent: 7, color: "#0ea5e9" },
    { name: "Boleto", percent: 5, color: "#64748b" },
  ],
  recentReceipts: [
    {
      id: "r1",
      patient: "Maria Silva",
      procedure: "Clareamento",
      professional: "Dra. Ana",
      paymentMethod: "PIX",
      date: "26/07/2026",
      amount: 850,
      status: "pago",
    },
    {
      id: "r2",
      patient: "João Pedro",
      procedure: "Implante",
      professional: "Dr. Carlos",
      paymentMethod: "Cartão Crédito",
      date: "25/07/2026",
      amount: 4200,
      status: "pago",
    },
    {
      id: "r3",
      patient: "Ana Costa",
      procedure: "Limpeza",
      professional: "Dra. Ana",
      paymentMethod: "Dinheiro",
      date: "25/07/2026",
      amount: 280,
      status: "pago",
    },
    {
      id: "r4",
      patient: "Pedro Lima",
      procedure: "Canal",
      professional: "Dr. Rafael",
      paymentMethod: "Boleto",
      date: "24/07/2026",
      amount: 1200,
      status: "pendente",
    },
  ],
  receivables: [
    {
      id: "ar1",
      patient: "Carla Mendes",
      document: "NF 1042",
      dueDate: "28/07/2026",
      amount: 1850,
      status: "a_vencer",
      daysOverdue: 0,
    },
    {
      id: "ar2",
      patient: "Bruno Alves",
      document: "ORC 882",
      dueDate: "20/07/2026",
      amount: 3200,
      status: "em_atraso",
      daysOverdue: 6,
    },
    {
      id: "ar3",
      patient: "Fernanda Dias",
      document: "NF 1038",
      dueDate: "30/07/2026",
      amount: 960,
      status: "a_vencer",
      daysOverdue: 0,
    },
  ],
  payables: [
    {
      id: "ap1",
      vendor: "Dental Lab SP",
      category: "Laboratório",
      dueDate: "27/07/2026",
      amount: 2450,
      account: "Itaú",
      status: "pendente",
    },
    {
      id: "ap2",
      vendor: "Energia SP",
      category: "Utilidades",
      dueDate: "05/08/2026",
      amount: 980,
      account: "Bradesco",
      status: "a_vencer",
    },
    {
      id: "ap3",
      vendor: "Material Odontológico",
      category: "Estoque",
      dueDate: "22/07/2026",
      amount: 1680,
      account: "Santander",
      status: "em_atraso",
    },
  ],
  convenios: [
    { id: "c1", name: "Unimed", amount: 12450, guides: 28, nextPayment: "05/08/2026" },
    { id: "c2", name: "Amil", amount: 8920, guides: 19, nextPayment: "08/08/2026" },
    { id: "c3", name: "Bradesco Dental", amount: 6780, guides: 14, nextPayment: "12/08/2026" },
    { id: "c4", name: "OdontoPrev", amount: 4300, guides: 11, nextPayment: "15/08/2026" },
  ],
  upcoming: [
    { id: "u1", when: "hoje", label: "Dental Lab SP — Laboratório", amount: 2450 },
    { id: "u2", when: "amanha", label: "Carla Mendes — NF 1042", amount: 1850 },
    { id: "u3", when: "semana", label: "Energia SP — Utilidades", amount: 980 },
    { id: "u4", when: "semana", label: "Amil — Repasse", amount: 8920 },
  ],
  alerts: [
    {
      id: "a1",
      title: "Contas vencidas",
      detail: "4 títulos em atraso (R$ 7.120)",
      priority: "alta",
    },
    {
      id: "a2",
      title: "Boletos vencendo",
      detail: "3 boletos nos próximos 3 dias",
      priority: "media",
    },
    {
      id: "a3",
      title: "Convênios atrasados",
      detail: "1 operadora com repasse pendente",
      priority: "media",
    },
    {
      id: "a4",
      title: "Parcelas em atraso",
      detail: "12 parcelas de pacientes",
      priority: "alta",
    },
    {
      id: "a5",
      title: "Pacientes inadimplentes",
      detail: "8 pacientes com saldo em aberto",
      priority: "baixa",
    },
  ],
  goal: { current: 128540, target: 150000 },
  movements: [
    {
      id: "m1",
      date: "26/07/2026",
      patient: "Maria Silva",
      description: "Clareamento dental",
      category: "Estética",
      professional: "Dra. Ana",
      costCenter: "Clínica",
      paymentMethod: "PIX",
      bankAccount: "Itaú",
      income: 850,
      expense: null,
      balance: 58420,
      status: "pago",
      notes: "",
    },
    {
      id: "m2",
      date: "26/07/2026",
      patient: "—",
      description: "Compra de insumos",
      category: "Estoque",
      professional: "—",
      costCenter: "Operacional",
      paymentMethod: "Transferência",
      bankAccount: "Bradesco",
      income: null,
      expense: 620,
      balance: 57570,
      status: "pago",
      notes: "Pedido #441",
    },
    {
      id: "m3",
      date: "25/07/2026",
      patient: "João Pedro",
      description: "Implante unitário",
      category: "Cirurgia",
      professional: "Dr. Carlos",
      costCenter: "Clínica",
      paymentMethod: "Cartão Crédito",
      bankAccount: "Santander",
      income: 4200,
      expense: null,
      balance: 58190,
      status: "pago",
      notes: "3x",
    },
    {
      id: "m4",
      date: "24/07/2026",
      patient: "Pedro Lima",
      description: "Endodontia",
      category: "Clínica",
      professional: "Dr. Rafael",
      costCenter: "Clínica",
      paymentMethod: "Boleto",
      bankAccount: "Itaú",
      income: 1200,
      expense: null,
      balance: 53990,
      status: "pendente",
      notes: "Aguardando compensação",
    },
    {
      id: "m5",
      date: "23/07/2026",
      patient: "—",
      description: "Aluguel da clínica",
      category: "Fixas",
      professional: "—",
      costCenter: "Administrativo",
      paymentMethod: "Transferência",
      bankAccount: "Itaú",
      income: null,
      expense: 8500,
      balance: 52790,
      status: "pago",
      notes: "",
    },
  ],
  summary: {
    saldoTotal: 58420,
    receitas: 128540,
    despesas: 42850,
    lucro: 85690,
    ticketMedio: 642,
    faturamentoDiario: 4280,
    faturamentoMensal: 128540,
    faturamentoAnual: 760000,
    pacientesPagantes: 214,
    convenios: 32450,
    receitasPrevistas: 74320,
    despesasPrevistas: 23650,
  },
  filterOptions: {
    professionals: ["Todos", "Dra. Ana", "Dr. Carlos", "Dr. Rafael"],
    convenios: ["Todos", "Unimed", "Amil", "Bradesco Dental", "Particular"],
    paymentMethods: ["Todos", "PIX", "Cartão Crédito", "Cartão Débito", "Dinheiro", "Boleto"],
    bankAccounts: ["Todas", "Itaú", "Bradesco", "Santander"],
    costCenters: ["Todos", "Clínica", "Operacional", "Administrativo"],
    categories: ["Todas", "Estética", "Cirurgia", "Clínica", "Estoque", "Fixas"],
    statuses: ["Todos", "Pago", "Pendente", "A vencer", "Em atraso"],
  },
};
